### PR TITLE
IMAGINGCLOUD-370 - Changed description and added documentation to correspond with corporate template

### PR DESCRIPTION
**Pull request by MaxCrank**
@aifeigin Please, check this initial version if it's OK for you so that I can proceed with other SDKs the same way.

### CODE REVIEW

**Comment by MaxCrank** [comment]
> 
> 
> Methods descriptions are unreadable in [SDK Documentation ](https://github.com/aspose-imaging-cloud/aspose-imaging-cloud-dotnet/blob/IMAGINGCLOUD-370/docs/API_README.md#documentation-for-api-endpoints)
> 
> Please review https://github.com/aspose-pdf-cloud/aspose-pdf-cloud-dotnet#documentation-for-models and make required layout changes.

@aifeigin Please, clarify the details. PDF team supports the docs in their own way, not by the requirements. We need to stick to the links in the task on how everything should be done.

**Comment by MaxCrank** [comment]
> 
> 
> Please provide manual on update of SDK documentation on release per release basics.

It will be done automatically by the code generator, i.e. we don't need anything specific on each release.

**Comment by MaxCrank** [comment]
> 
> 
> Please add reference to the SDK landing page to the short description of the current SDK repository, i.e. :
> 
> This repository contains [Aspose.Imaging Cloud .NET SDK](https://products.aspose.cloud/imaging/net) source code. This SDK allows you to work with Aspose.Imaging Cloud REST APIs in your .NET applications quickly and easily, with zero initial cost.

Done.

**Comment by MaxCrank** [comment]
> 
> 
> > Please, clarify the details. PDF team supports the docs in their own way, not by the requirements. We need to stick to the links in the task on how everything should be done.
> 
> You're complete right in general, but if you can, please make total width of 1st three columns of
> Documentation for API Endpoints table equal to the width of container article to place descriptions to second screen on horizontal scrolling, like Pdf team did, that looks more neatly than your current design.

@aifeigin Markdown tables are very simple and don't provide such settings. Our layout is identical with PDF on Firefox without any horizontal scrollbar (I'm using it and that's why have asked for clarification) and different on Chrome (with scrollbar present) only because dynamic layout behaves differently on these browsers regarding the contents of tables' cells. I.e. it's a GitHub layout problem we can't affect.

**Comment by aifeigin** [comment]
> Markdown tables are very simple and don't provide such settings

Thus you may leave it as is, complete .NET changes and do the the same for other SDKs

**Pull request merged**
